/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myWebServices.havadurumu;

 
import com.myWebServices.havadurumu.dto.MainCategoryDTO; 
import com.myWebServices.havadurumu.dto.SubCategoryDTO;
import helper.Helper;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;
import table.TableDetail;
import table.TableDetailModel;
import webservice.WebService;

/**
 *
 * @author isoba
 */
public class myView extends javax.swing.JFrame {

    private  void CreatMenu() {
         WebService webservice=new WebService();
        try {
            String json=webservice.getMyJson("http://www.json-generator.com/api/json/get/bUvaCuYlgy?indent=2");
            List<MainCategoryDTO> allTree=webservice.getEmployessList(json);
            CreateJTree(allTree);
        } catch (IOException ex) {
            Logger.getLogger(myView.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }

    /**
     * Creates new form myView
     */
    public myView() {
        initComponents();
        CreatMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setPreferredSize(new java.awt.Dimension(63, 16));
        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Açıklama");
        jLabel1.setToolTipText("");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1513, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myView().setVisible(true);
              
            }
        });
        
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private void  CreateJTree(List<MainCategoryDTO> allTree) {
         
        
         DefaultMutableTreeNode root = new DefaultMutableTreeNode("Listem");
        for (int i = 0; i < allTree.size(); i++) {
          MainCategoryDTO  mainCategory = allTree.get(i);
          DefaultMutableTreeNode mainCategoryTree = new DefaultMutableTreeNode(mainCategory.getName());
          CreatSubCategory(mainCategory.getList(),mainCategoryTree);
          root.add(mainCategoryTree);
        }       
      
        
        DefaultTreeModel model = new DefaultTreeModel(root);        
        jTree1.setModel(model);  
        jTree1.setRootVisible(false);
        jTree1.addTreeSelectionListener((javax.swing.event.TreeSelectionEvent evt) -> {
            JTree1ValueChanged(evt);
         });
         
    }
  
    private void CreatSubCategory(List<SubCategoryDTO> subCategoryList,DefaultMutableTreeNode mainCategoryTree) {
      for (int i = 0; i < subCategoryList.size(); i++) {
          SubCategoryDTO subCategoryDTO=subCategoryList.get(i);
          DefaultMutableTreeNode treeNode=new DefaultMutableTreeNode(subCategoryDTO.getSubName());
          treeNode.setUserObject(subCategoryDTO);
          mainCategoryTree.add(treeNode);
             
        }
  
    }
    
     public void JTree1ValueChanged( TreeSelectionEvent tse ) {
      TreePath path = tse.getPath();
      DefaultMutableTreeNode node = (DefaultMutableTreeNode) path.getLastPathComponent();
      SubCategoryDTO subCategoryDTO=(SubCategoryDTO) node.getUserObject();
      CreatTableDetail(subCategoryDTO);
             
     
    }

    private void CreatTableDetail(SubCategoryDTO subCategoryDTO) {
        String[] columns = {"Id ","Adı", "Yayın Yılı", "Ülke", "İmdb","Resim","Açıklama"};
        Object[][] data =Helper.ListSubToObjectArry(subCategoryDTO.getListDetail());
        TableDetailModel model = new TableDetailModel(columns, data);    
        jTable1.setModel(model);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            
              
            try {
                String resimUrl =jTable1.getValueAt(jTable1.getSelectedRow(),5).toString();
                String aciklama =jTable1.getValueAt(jTable1.getSelectedRow(),6).toString();
                jLabel2.setText(aciklama);
                SetImageWithUrl(resimUrl);
            } catch (IOException ex) {
                Logger.getLogger(myView.class.getName()).log(Level.SEVERE, null, ex);
            }
              
            
            
        }
    });
       
        
        
        
     }

    private void SetImageWithUrl(String urlImage) throws IOException {
         
        try {
            System.out.println("Resim URL>>>>"+ urlImage);
            URL url;
            url = new URL(urlImage);
            BufferedImage bufferedImage = ImageIO.read(url);
            ImageIcon image = new ImageIcon(bufferedImage);
            jLabel3.setIcon(image); 
        } catch (Exception ex) {
            Logger.getLogger(myView.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }
}
